import { useState } from 'react';
import { StyleSheet, View, ViewStyle } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { colors, radius, spacing, hairline } from '../theme';
import { Text } from './Text';
import { PressableScale } from './PressableScale';

/**
 * The two things this product must say, said once.
 *
 * Both paragraphs are real disclosures with a real reason: paint on a screen is
 * not paint on a wall, and an AI preview is a guide rather than a promise. The
 * design pasted them verbatim into five and six screens respectively, at full
 * length, which is how a genuine caution becomes wallpaper the eye skips.
 *
 * So the text lives here once and is shown collapsed — one line of summary the
 * eye can take in, expanding to the full paragraph on tap. It is present
 * everywhere it needs to be, and it is readable in the one place someone
 * actually wants to read it.
 */
export const DISCLOSURE = {
  colour: {
    title: 'About these colours',
    summary: 'Screens shift colour — check the shade card at the counter.',
    body:
      'Shade colours are taken from the paint companies’ own shade cards and fan decks. ' +
      'Screens, printing and lighting all shift colour, so what you see here can differ ' +
      'from the paint on the wall. Always check the physical shade card at the counter ' +
      'before you buy.',
  },
  ai: {
    title: 'About AI previews',
    summary: 'Previews are AI-generated — a guide, not the finished wall.',
    body:
      'Previews are generated by AI. They are a guide to how a colour might look, not an ' +
      'exact picture of the finished wall — edges, textures and lighting can come out ' +
      'differently, and results are not guaranteed.',
  },
} as const;

export type DisclosureKind = keyof typeof DISCLOSURE;

export interface DisclosureProps {
  kind: DisclosureKind;
  /** Start open where the disclosure is the point of the screen (the board confirm). */
  defaultOpen?: boolean;
  style?: ViewStyle;
}

export function Disclosure({ kind, defaultOpen = false, style }: DisclosureProps) {
  const [open, setOpen] = useState(defaultOpen);
  const d = DISCLOSURE[kind];

  return (
    <PressableScale
      onPress={() => setOpen((o) => !o)}
      haptic="tap"
      activeScale={0.99}
      accessibilityRole="button"
      accessibilityState={{ expanded: open }}
      accessibilityLabel={`${d.title}. ${open ? d.body : d.summary}`}
      style={StyleSheet.flatten([styles.wrap, style])}
    >
      <View style={styles.head}>
        <Ionicons name="information-circle-outline" size={15} color={colors.fgMute} />
        <Text variant="caption" style={styles.summary} numberOfLines={open ? undefined : 2}>
          {open ? d.body : d.summary}
        </Text>
        <Ionicons name={open ? 'chevron-up' : 'chevron-down'} size={13} color={colors.fgMute} />
      </View>
    </PressableScale>
  );
}

const styles = StyleSheet.create({
  wrap: {
    borderRadius: radius.cardTight,
    borderWidth: hairline,
    borderColor: colors.glassEdgeSoft,
    backgroundColor: colors.glass,
    padding: spacing.md,
  },
  head: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: spacing.sm,
  },
  summary: {
    flex: 1,
  },
});
